<?php
$data1 = array(
  array(
    'Gender' => 'Male',
    'Car ownership' => '0',
    'Travel cost' => 'Cheap',
    'Income level' => 'Low',
    'Transportation' => 'Bus',
  ),
  array(
    'Gender' => 'Male',
    'Car ownership' => '1',
    'Travel cost' => 'Cheap',
    'Income level' => 'Medium',
    'Transportation' => 'Bus',
  ),
  array(
    'Gender' => 'Female',
    'Car ownership' => '1',
    'Travel cost' => 'Cheap',
    'Income level' => 'Medium',
    'Transportation' => 'Train',
  ),
  array(
    'Gender' => 'Female',
    'Car ownership' => '0',
    'Travel cost' => 'Cheap',
    'Income level' => 'Low',
    'Transportation' => 'Bus',
  ),
  array(
    'Gender' => 'Male',
    'Car ownership' => '1',
    'Travel cost' => 'Cheap',
    'Income level' => 'Medium',
    'Transportation' => 'Bus',
  ),
  array(
    'Gender' => 'Male',
    'Car ownership' => '0',
    'Travel cost' => 'Standard',
    'Income level' => 'Medium',
    'Transportation' => 'Train',
  ),
  array(
    'Gender' => 'Female',
    'Car ownership' => '1',
    'Travel cost' => 'Standard',
    'Income level' => 'Medium',
    'Transportation' => 'Train',
  ),
  array(
    'Gender' => 'Female',
    'Car ownership' => '1',
    'Travel cost' => 'Expensive',
    'Income level' => 'High',
    'Transportation' => 'Car',
  ),
  array(
    'Gender' => 'Male',
    'Car ownership' => '2',
    'Travel cost' => 'Expensive',
    'Income level' => 'Medium',
    'Transportation' => 'Car',
  ),
  array(
    'Gender' => 'Female',
    'Car ownership' => '2',
    'Travel cost' => 'Expensive',
    'Income level' => 'High',
    'Transportation' => 'Car',
  ),
);

$data2 = array(
  array(
    'outlook' => 'sunny',
    'temperature' => 'hot',
    'humidity' => 'high',
    'wind' => 'weak',
    'decision' => 'no',
  ),
  array(
    'outlook' => 'sunny',
    'temperature' => 'hot',
    'humidity' => 'high',
    'wind' => 'strong',
    'decision' => 'no',
  ),
  array(
    'outlook' => 'overcast',
    'temperature' => 'hot',
    'humidity' => 'high',
    'wind' => 'weak',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'rain',
    'temperature' => 'mild',
    'humidity' => 'high',
    'wind' => 'weak',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'rain',
    'temperature' => 'cool',
    'humidity' => 'normal',
    'wind' => 'weak',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'rain',
    'temperature' => 'cool',
    'humidity' => 'normal',
    'wind' => 'strong',
    'decision' => 'no',
  ),
  array(
    'outlook' => 'overcast',
    'temperature' => 'cool',
    'humidity' => 'normal',
    'wind' => 'strong',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'sunny',
    'temperature' => 'mild',
    'humidity' => 'high',
    'wind' => 'weak',
    'decision' => 'no',
  ),
  array(
    'outlook' => 'sunny',
    'temperature' => 'cool',
    'humidity' => 'normal',
    'wind' => 'weak',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'rain',
    'temperature' => 'mild',
    'humidity' => 'normal',
    'wind' => 'weak',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'sunny',
    'temperature' => 'mild',
    'humidity' => 'normal',
    'wind' => 'strong',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'overcast',
    'temperature' => 'mild',
    'humidity' => 'high',
    'wind' => 'strong',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'overcast',
    'temperature' => 'hot',
    'humidity' => 'normal',
    'wind' => 'weak',
    'decision' => 'yes',
  ),
  array(
    'outlook' => 'rain',
    'temperature' => 'mild',
    'humidity' => 'high',
    'wind' => 'strong',
    'decision' => 'no',
  ),
);
